spring:
  datasource:
    url: jdbc:mysql://172.16.0.226:3306/ids_db?characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: ids_db_1qazZAQ!
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.16.0.226
    port: 6379
    password: nssa_redis_1qazZAQ!
    max-idle: 100
    min-idle: 1
    max-active: 1000
    max-wait: -1
    maxRedirects: 3
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

es:
  elasticsearch:
    username:
    password:
    hostlist: 172.16.0.226:9201