spring:
  application:
    name: service-asset
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件大小
      max-request-size: 500MB
      enabled: true #开启
server:
  port: 8087

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

logging.level.com.jwell56.security.cloud.service.asset.mapper: debug